-- 코드를 입력하세요
SELECT BD.TITLE, BD.BOARD_ID, RL.REPLY_ID, RL.WRITER_ID, RL.CONTENTS,  DATE_FORMAT(RL.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD BD 
JOIN USED_GOODS_REPLY RL ON BD.BOARD_ID = RL.BOARD_ID
WHERE BD.CREATED_DATE like '2022-10%'
ORDER BY RL.CREATED_DATE ASC, BD.TITLE ASC


# SELECT BD.TITLE, BD.BOARD_ID, RL.REPLY_ID, RL.WRITER_ID, RL.CONTENTS, RL.CREATED_DATE
# FROM USED_GOODS_BOARD BD 
# JOIN USED_GOODS_REPLY RL ON BD.BOARD_ID = RL.BOARD_ID;